name: Lint
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸš€ Run yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: roles/js_mac/files/dotfiles/.config/yamllint/config
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸš€ Lint Ansible Playbook
        uses: ansible/ansible-lint-action@4.1.0
        with:
          override-deps: |
            ansible-lint==5.3.2
          targets: .
